### ISSUE TITLE
Break code into smaller modules

### ISSUE THREAD

**Issue by timothymtorres** [alexeagleson/arctic-lab#2]
Hello again!  

After you posted in /r/roguelikedev I was examining your repo and have a few helpful suggestions.  A good programming practice is to fragment your code into smaller pieces so that the file(s) don't get too large.  It makes it easier to navigate, manage, and tremendously improves code readability.  I would suggest you do this with different data:  maps, items, characters, etc.

Another thing that would probably be helpful is to experiment with the structure of your directory.  Consider a "audio" folder for sounds, "code" folder for code, "graphics" folder for maps, particle effects, etc.

The only time where having a single large file *might* be a good idea is if you were building a library for others to use.

**Comment by alexeagleson** [comment]
Thank you!  Appreciate the tips.  Definitely will put them into practice for the next project

Alex
